// <auto-generated />
namespace Week9Day2.Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DateTime2inIdentityModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateTime2inIdentityModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201512152047430_DateTime2inIdentityModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
